In [1]:
import numpy as np
import pandas as pd

In [2]:
iris = pd.read_csv('Iris.csv')
del iris['Id']
iris

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
0              5.1           3.5            1.4           0.2     Iris-setosa
1              4.9           3.0            1.4           0.2     Iris-setosa
2              4.7           3.2            1.3           0.2     Iris-setosa
3              4.6           3.1            1.5           0.2     Iris-setosa
4              5.0           3.6            1.4           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
145            6.7           3.0            5.2           2.3  Iris-virginica
146            6.3           2.5            5.0           1.9  Iris-virginica
147            6.5           3.0            5.2           2.0  Iris-virginica
148            6.2           3.4            5.4           2.3  Iris-virginica
149            5.9           3.0            5.1           1.8  Iris-virginica

[150 rows x 5 columns]

In [3]:
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()
iris['Species']= label_encoder.fit_transform(iris['Species'])
iris

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0              5.1           3.5            1.4           0.2        0
1              4.9           3.0            1.4           0.2        0
2              4.7           3.2            1.3           0.2        0
3              4.6           3.1            1.5           0.2        0
4              5.0           3.6            1.4           0.2        0
..             ...           ...            ...           ...      ...
145            6.7           3.0            5.2           2.3        2
146            6.3           2.5            5.0           1.9        2
147            6.5           3.0            5.2           2.0        2
148            6.2           3.4            5.4           2.3        2
149            5.9           3.0            5.1           1.8        2

[150 rows x 5 columns]

In [4]:
y = iris['Species']
X = iris.drop(columns='Species')

In [5]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split

In [6]:
neigh = KNeighborsClassifier(n_neighbors=3)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,random_state=42)

neigh.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [7]:
print('Overall Accuracy = %',neigh.score(X_test, y_test)*100)

Overall Accuracy = % 100.0

In [8]:
from sklearn.metrics import classification_report

target_names = ['Iris-setosa', 'Iris-versicolor' , 'Iris-virginica']

y_true = y_test

y_pred = neigh.predict(X_test)

print(classification_report(y_true, y_pred, target_names=target_names))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       1.00      1.00      1.00         9
 Iris-virginica       1.00      1.00      1.00        11

       accuracy                           1.00        30
      macro avg       1.00      1.00      1.00        30
   weighted avg       1.00      1.00      1.00        30

In [9]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_true,y_pred)

array([[10,  0,  0],
       [ 0,  9,  0],
       [ 0,  0, 11]], dtype=int64)

In [10]:
new_data = pd.DataFrame(np.array([[1,2,3,4],[3,2,6,8],[1.7,4,2,2],[6,3,1,8],[5,6,2,4],
                      [4,2,1,4],[1,2,3,8],[6.7,8,2.4,2],[4,3,1,8],[4,3,2,4],
                      [2,2,4,4],[6,2,2,8],[3.7,4,5,2],[7,3,1,8],[2,3,2,4],
                      [1,1,1,4],[5,1,2,8],[5.7,4,2,2],[2,3,1,8],[8,6,8,0.3]]),
                       columns=['SepalLengthCm','SepalWidthCm','PetalLengthCm','PetalWidthCm'])

In [11]:
new_pred = neigh.predict(new_data)
new_pred

array([1, 2, 0, 2, 0, 0, 2, 0, 2, 1, 1, 2, 2, 2, 1, 0, 2, 0, 1, 2])

In [12]:
w = pd.DataFrame(new_pred,columns=['Species'])

In [13]:
output = pd.concat([new_data,w],axis=1)

In [14]:
output['Species'] = output['Species'].replace(0,'setora')
output['Species'] = output['Species'].replace(1,'versicolor')
output['Species'] = output['Species'].replace(2,'virginica')

In [15]:
output

    SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm     Species
0             1.0           2.0            3.0           4.0  versicolor
1             3.0           2.0            6.0           8.0   virginica
2             1.7           4.0            2.0           2.0      setora
3             6.0           3.0            1.0           8.0   virginica
4             5.0           6.0            2.0           4.0      setora
5             4.0           2.0            1.0           4.0      setora
6             1.0           2.0            3.0           8.0   virginica
7             6.7           8.0            2.4           2.0      setora
8             4.0           3.0            1.0           8.0   virginica
9             4.0           3.0            2.0           4.0  versicolor
10            2.0           2.0            4.0           4.0  versicolor
11            6.0           2.0            2.0           8.0   virginica
12            3.7           4.0            5.0           2.0   virginica
13            7.0           3.0            1.0           8.0   virginica
14            2.0           3.0            2.0           4.0  versicolor
15            1.0           1.0            1.0           4.0      setora
16            5.0           1.0            2.0           8.0   virginica
17            5.7           4.0            2.0           2.0      setora
18            2.0           3.0            1.0           8.0  versicolor
19            8.0           6.0            8.0           0.3   virginica